# Generated by Django 4.2.13 on 2024-07-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='Pro_images',
        ),
    ]
