# Generated by Django 4.2.13 on 2024-07-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_images_pro_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_images',
            name='img_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
