# Generated by Django 4.2.13 on 2024-07-05 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pro_images_img_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_images',
            name='img_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
