# Generated by Django 4.2.13 on 2024-07-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pro_images_img_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/addimgs'),
        ),
        migrations.AlterField(
            model_name='pro_images',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/addimgs'),
        ),
    ]
